apiVersion: apps/v1
kind: Deployment
metadata:
  name: opa
spec:
  selector:
    matchLabels:
      app: opa
  template:
    metadata:
      labels:
        app: opa
    spec:
      containers:
      - name: opa
        image: ghcr.io/dettanym/prose-opa:latest@sha256:465bd136d44831ca0acdcf3ea87ed9f8ec7dbf54df538defe2104d1278994e4b
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
