---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-demo
spec:
  interval: 15m
  chart:
    spec:
      chart: opentelemetry-demo
      version: 0.23.0
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
        namespace: flux-system
  maxHistory: 3
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    crds: CreateReplace
  uninstall:
    keepHistory: false
  values:
    components:
      frontend:
        envOverrides:
          - name: PUBLIC_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            value: http://otel-demo-collector.${SECRET_DOMAIN}/v1/traces

      frontendProxy:
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: otel-demo.${SECRET_DOMAIN}
              paths:
                - path: /
                  pathType: Prefix
                  port: 8080
    opentelemetry-collector:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: otel-demo-collector.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                port: 4318
