---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: statefulset
    image:
      repository: docker.io/fallenbagel/jellyseerr
      tag: 1.5.0@sha256:3ff0d7af326f4e6db4dbe8679284a4230c9fd4205f59ecc9637ecfbdedb473c3
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        ports:
          http:
            port: &port 5055
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "seer.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
    volumeClaimTemplates:
      - name: config
        mountPath: /app/config
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: local-path
    resources:
      requests:
        cpu: 100m
        memory: 250Mi
      limits:
        memory: 1Gi
